# Generated by Django 5.2.7 on 2025-10-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
