# Generated by Django 5.2.7 on 2025-10-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0003_alter_user_email_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='driver_to_rider_distance',
            field=models.FloatField(default=0),
        ),
    ]
