# Generated by Django 5.2.7 on 2025-10-25 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0004_ride_driver_to_rider_distance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='driver_to_rider_distance',
            new_name='pickup_distance',
        ),
    ]
